USE SREERAGVV;
CREATE TABLE SCHOOL
(RENO INT (5),
NAME VARCHAR(15),
 MARKS INT(3));
 
 DESCRIBE SCHOOL;
 
 INSERT INTO SCHOOL VALUES(94,'SREERAG',90);
 
 INSERT INTO SCHOOL VALUES(95,'SREEKANTH',80);

INSERT INTO SCHOOL VALUES(96,'SREEREKHA',85);
SELECT * FROM SCHOOL;
SELECT RENO FROM SCHOOL;

